import React, { useState } from 'react';
import {
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  AlertTriangle,
  ExternalLink,
  Lock,
  UserX,
  Clock,
  KeyRound,
  CheckCircle2,
  Copy,
  Check,
  RefreshCw,
  Info,
  Shield,
  FileCheck2,
  Volume2,
} from 'lucide-react';
import { EmailAnalysisResult, TranslationStrings } from '../types';

interface Props {
  result: EmailAnalysisResult;
  onReset: () => void;
  onTriggerEmergencyAlert?: () => void;
  translations: TranslationStrings;
}

export const AnalysisResults: React.FC<Props> = ({
  result,
  onReset,
  onTriggerEmergencyAlert,
  translations,
}) => {
  const [copied, setCopied] = useState(false);

  const getThreatColorDetails = (level: string) => {
    switch (level) {
      case 'CRITICAL_PHISH':
        return {
          title: translations.criticalBadge,
          bgColor: 'bg-red-950/70',
          borderColor: 'border-red-600',
          textColor: 'text-red-400',
          badgeBg: 'bg-red-600 text-white',
          glowClass: 'shadow-red-600/30',
          icon: <ShieldX className="w-9 h-9 text-red-500 animate-pulse" />,
          gaugeColor: '#ef4444',
        };
      case 'HIGH_RISK':
        return {
          title: translations.highRiskBadge,
          bgColor: 'bg-red-950/40',
          borderColor: 'border-red-700',
          textColor: 'text-red-400',
          badgeBg: 'bg-red-700 text-white',
          glowClass: 'shadow-red-900/30',
          icon: <ShieldAlert className="w-9 h-9 text-red-400" />,
          gaugeColor: '#dc2626',
        };
      case 'SUSPICIOUS':
        return {
          title: translations.suspiciousBadge,
          bgColor: 'bg-amber-950/30',
          borderColor: 'border-amber-700/70',
          textColor: 'text-amber-400',
          badgeBg: 'bg-amber-600 text-white',
          glowClass: 'shadow-amber-900/20',
          icon: <AlertTriangle className="w-9 h-9 text-amber-400" />,
          gaugeColor: '#f59e0b',
        };
      case 'SAFE':
      default:
        return {
          title: translations.safeBadge,
          bgColor: 'bg-emerald-950/20',
          borderColor: 'border-emerald-700/60',
          textColor: 'text-emerald-400',
          badgeBg: 'bg-emerald-600 text-white',
          glowClass: 'shadow-emerald-900/20',
          icon: <ShieldCheck className="w-9 h-9 text-emerald-400" />,
          gaugeColor: '#10b981',
        };
    }
  };

  const threatStyle = getThreatColorDetails(result.threatLevel);

  const handleCopyReport = () => {
    const reportText = `=== KAWACH AI EMAIL THREAT REPORT ===
Verdict: ${result.threatLevel} (Risk Score: ${result.riskScore}/100)
Summary: ${result.verdictSummary}

Sender Status: ${result.senderAuthenticity.status} - ${result.senderAuthenticity.details}
Urgency Trap: ${result.urgencyAnalysis.isUrgent ? 'YES' : 'NO'} - ${result.urgencyAnalysis.details}
Links Checked: ${result.linksAnalysis.totalLinks} links (${result.linksAnalysis.suspiciousLinksCount} suspicious) - ${result.linksAnalysis.details}
Credential Theft Risk: ${result.credentialHarvestingRisk ? 'HIGH' : 'LOW'}

Indicators of Compromise (IoCs):
${result.indicatorsOfCompromise.map((ioc) => `- ${ioc}`).join('\n')}

Recommendations:
${result.recommendations.map((rec) => `- ${rec}`).join('\n')}

MITRE ATT&CK: ${result.mitreTechniques.join(', ')}
Generated by KAWACH AI Cyber Armor.`;

    navigator.clipboard.writeText(reportText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <div
      id="analysis-results-container"
      className="space-y-6 animate-fade-in"
    >
      {/* Notice bar if heuristic fallback */}
      {result.notice && (
        <div className="flex items-center gap-2 p-3 rounded-xl bg-zinc-900/90 border border-red-900/40 text-xs text-zinc-300">
          <Info className="w-4 h-4 text-red-400 shrink-0" />
          <span>{result.notice}</span>
        </div>
      )}

      {/* Main Threat Verdict Card */}
      <div
        id="main-threat-verdict-card"
        className={`p-6 sm:p-8 rounded-2xl border ${threatStyle.borderColor} ${threatStyle.bgColor} shadow-2xl ${threatStyle.glowClass} relative overflow-hidden backdrop-blur-xl`}
      >
        {/* Background accent */}
        <div className="absolute top-0 right-0 -mt-10 -mr-10 w-48 h-48 bg-red-600/10 rounded-full blur-3xl pointer-events-none" />

        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6 relative z-10">
          {/* Verdict Info */}
          <div className="flex items-start gap-4 sm:gap-6">
            <div className="p-3.5 rounded-xl bg-black border border-red-900/40 shrink-0 shadow-inner">
              {threatStyle.icon}
            </div>
            <div>
              <div className="flex items-center gap-3 flex-wrap">
                <span
                  id="threat-level-badge"
                  className={`text-xs font-black px-3.5 py-1 rounded-full uppercase tracking-widest font-mono shadow-md ${threatStyle.badgeBg}`}
                >
                  {threatStyle.title}
                </span>
                {result.language && (
                  <span className="text-xs text-gray-400 font-mono bg-black/60 px-2.5 py-0.5 rounded border border-red-900/30">
                    Language: {result.language}
                  </span>
                )}
              </div>
              <h3 className="text-xl sm:text-2xl font-black text-white mt-2.5 tracking-tight">
                {translations.threatLevelTitle}
              </h3>
              <p className="text-sm text-gray-300 mt-2 leading-relaxed max-w-2xl">
                {result.verdictSummary}
              </p>

              {/* Speak Alert Quick Trigger */}
              {onTriggerEmergencyAlert && (
                <div className="mt-3.5">
                  <button
                    id="email-speak-alert-btn"
                    type="button"
                    onClick={onTriggerEmergencyAlert}
                    className="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-xl bg-red-600 hover:bg-red-500 text-white text-xs font-black uppercase tracking-wider transition-all shadow-[0_0_15px_rgba(220,38,38,0.4)] cursor-pointer"
                  >
                    <Volume2 className="w-3.5 h-3.5 animate-pulse" />
                    <span>{translations.speakAlertButton || '🚨 Speak Emergency Alert'}</span>
                  </button>
                </div>
              )}
            </div>
          </div>

          {/* Risk Score Dial */}
          <div
            id="risk-score-dial"
            className="flex items-center gap-4 bg-black/80 border border-red-900/40 rounded-2xl p-4 sm:p-5 shrink-0 self-start lg:self-auto shadow-xl"
          >
            <div className="relative w-20 h-20 flex items-center justify-center">
              {/* Circular Gauge */}
              <svg className="w-full h-full -rotate-90" viewBox="0 0 36 36">
                <path
                  className="text-zinc-900"
                  strokeWidth="3.5"
                  stroke="currentColor"
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
                <path
                  strokeDasharray={`${result.riskScore}, 100`}
                  strokeWidth="3.5"
                  strokeLinecap="round"
                  stroke={threatStyle.gaugeColor}
                  fill="none"
                  d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                />
              </svg>
              <div className="absolute flex flex-col items-center justify-center">
                <span className="text-xl font-black text-white font-mono leading-none">
                  {result.riskScore}
                </span>
                <span className="text-[10px] text-gray-400 font-mono">/100</span>
              </div>
            </div>
            <div>
              <div className="text-xs font-bold text-gray-400 uppercase tracking-widest">
                {translations.riskScoreTitle}
              </div>
              <div className="text-xs font-mono font-bold text-white mt-1">
                {result.riskScore >= 75
                  ? 'CRITICAL THREAT'
                  : result.riskScore >= 50
                  ? 'ELEVATED HAZARD'
                  : result.riskScore >= 25
                  ? 'SUSPICIOUS PATTERNS'
                  : 'MINIMAL RISK'}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* 4 Core Diagnostic Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* 1. Sender & Domain Spoofing */}
        <div
          id="sender-auth-card"
          className="p-5 rounded-2xl bg-[#0a0a0a] border border-red-900/30 hover:border-red-600/50 transition-all"
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2 text-sm font-bold text-white">
              <UserX className="w-4 h-4 text-red-500" />
              <span>{translations.senderAuthTitle}</span>
            </div>
            <span
              className={`text-[10px] font-mono px-2.5 py-0.5 rounded font-bold uppercase tracking-wider ${
                result.senderAuthenticity.status.includes('SPOOFED') || result.senderAuthenticity.status.includes('FAILED')
                  ? 'bg-red-950 text-red-400 border border-red-800'
                  : result.senderAuthenticity.status.includes('SUSPICIOUS')
                  ? 'bg-amber-950 text-amber-400 border border-amber-800'
                  : 'bg-emerald-950 text-emerald-400 border border-emerald-800'
              }`}
            >
              {result.senderAuthenticity.status}
            </span>
          </div>
          <p className="text-xs text-gray-300 leading-relaxed">
            {result.senderAuthenticity.details}
          </p>
        </div>

        {/* 2. Psychological Urgency Traps */}
        <div
          id="urgency-trap-card"
          className="p-5 rounded-2xl bg-[#0a0a0a] border border-red-900/30 hover:border-red-600/50 transition-all"
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2 text-sm font-bold text-white">
              <Clock className="w-4 h-4 text-red-500" />
              <span>{translations.urgencyTitle}</span>
            </div>
            <span
              className={`text-[10px] font-mono px-2.5 py-0.5 rounded font-bold uppercase tracking-wider ${
                result.urgencyAnalysis.isUrgent
                  ? 'bg-red-950 text-red-400 border border-red-800'
                  : 'bg-zinc-900 text-gray-400 border border-zinc-800'
              }`}
            >
              {result.urgencyAnalysis.isUrgent ? 'URGENCY DETECTED' : 'NORMAL PACE'}
            </span>
          </div>
          <p className="text-xs text-gray-300 leading-relaxed">
            {result.urgencyAnalysis.details}
          </p>
        </div>

        {/* 3. Link & URL Inspection */}
        <div
          id="links-inspection-card"
          className="p-5 rounded-2xl bg-[#0a0a0a] border border-red-900/30 hover:border-red-600/50 transition-all"
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2 text-sm font-bold text-white">
              <ExternalLink className="w-4 h-4 text-red-500" />
              <span>{translations.linksTitle}</span>
            </div>
            <span
              className={`text-[10px] font-mono px-2.5 py-0.5 rounded font-bold uppercase tracking-wider ${
                result.linksAnalysis.suspiciousLinksCount > 0
                  ? 'bg-red-950 text-red-400 border border-red-800'
                  : 'bg-emerald-950 text-emerald-400 border border-emerald-800'
              }`}
            >
              {result.linksAnalysis.suspiciousLinksCount > 0
                ? `${result.linksAnalysis.suspiciousLinksCount} Malicious Links`
                : 'No Malicious Links'}
            </span>
          </div>
          <p className="text-xs text-gray-300 leading-relaxed">
            {result.linksAnalysis.details}
          </p>
        </div>

        {/* 4. Credential & Financial Harvesting Risk */}
        <div
          id="credential-risk-card"
          className="p-5 rounded-2xl bg-[#0a0a0a] border border-red-900/30 hover:border-red-600/50 transition-all"
        >
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2 text-sm font-bold text-white">
              <KeyRound className="w-4 h-4 text-red-500" />
              <span>{translations.credentialRiskTitle}</span>
            </div>
            <span
              className={`text-[10px] font-mono px-2.5 py-0.5 rounded font-bold uppercase tracking-wider ${
                result.credentialHarvestingRisk
                  ? 'bg-red-950 text-red-400 border border-red-800'
                  : 'bg-emerald-950 text-emerald-400 border border-emerald-800'
              }`}
            >
              {result.credentialHarvestingRisk ? 'HIGH RISK' : 'LOW RISK'}
            </span>
          </div>
          <p className="text-xs text-gray-300 leading-relaxed">
            {result.credentialHarvestingRisk
              ? 'Attempts to solicit passwords, OTPs, Aadhaar/PAN, banking credentials, or fake APK installation.'
              : 'No overt password, OTP, or financial harvesting solicitations found in content.'}
          </p>
        </div>
      </div>

      {/* Indicators of Compromise (IoCs) */}
      <div
        id="iocs-section"
        className="p-6 rounded-2xl bg-[#0a0a0a] border border-red-900/30"
      >
        <h4 className="text-sm font-bold text-white mb-4 flex items-center gap-2 uppercase tracking-wider">
          <AlertTriangle className="w-4 h-4 text-red-500" />
          <span>{translations.iocsTitle}</span>
        </h4>
        <div className="space-y-2">
          {result.indicatorsOfCompromise.map((ioc, idx) => (
            <div
              key={idx}
              className="flex items-start gap-3 p-3 rounded-xl bg-black/60 border border-red-900/20 text-xs text-gray-300"
            >
              <div className="w-1.5 h-1.5 rounded-full bg-red-500 mt-1.5 shrink-0" />
              <span className="leading-relaxed font-mono">{ioc}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Actionable Recommendations */}
      <div
        id="recommendations-section"
        className="p-6 rounded-2xl bg-[#0a0a0a] border border-red-900/30"
      >
        <h4 className="text-sm font-bold text-white mb-4 flex items-center gap-2 uppercase tracking-wider">
          <CheckCircle2 className="w-4 h-4 text-emerald-400" />
          <span>{translations.recommendationsTitle}</span>
        </h4>
        <div className="space-y-2.5">
          {result.recommendations.map((rec, idx) => (
            <div
              key={idx}
              className="flex items-start gap-3 p-3.5 rounded-xl bg-black/60 border border-zinc-800/80 text-xs text-gray-200"
            >
              <Shield className="w-4 h-4 text-red-500 mt-0.5 shrink-0" />
              <span className="leading-relaxed font-medium">{rec}</span>
            </div>
          ))}
        </div>
      </div>

      {/* MITRE ATT&CK Mapping */}
      {result.mitreTechniques && result.mitreTechniques.length > 0 && (
        <div
          id="mitre-section"
          className="p-4 rounded-xl bg-black/80 border border-red-900/20 flex flex-wrap items-center gap-2 text-xs"
        >
          <span className="font-bold text-gray-400 uppercase tracking-wider font-mono">
            {translations.mitreTitle}:
          </span>
          {result.mitreTechniques.map((tech, idx) => (
            <span
              key={idx}
              className="px-2.5 py-1 rounded bg-red-950/30 border border-red-900/40 text-red-400 font-mono text-[11px]"
            >
              {tech}
            </span>
          ))}
        </div>
      )}

      {/* Bottom Action Controls */}
      <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
        <button
          id="reset-analysis-btn"
          onClick={onReset}
          className="flex items-center gap-2 px-5 py-3 rounded-xl bg-black hover:bg-zinc-900 border border-zinc-800 hover:border-red-900/60 text-xs font-bold uppercase tracking-wider text-gray-300 hover:text-white transition-all cursor-pointer"
        >
          <RefreshCw className="w-3.5 h-3.5" />
          <span>{translations.resetAnalysis}</span>
        </button>

        <button
          id="copy-report-btn"
          onClick={handleCopyReport}
          className="flex items-center gap-2 px-6 py-3 rounded-xl bg-red-600 hover:bg-red-700 text-white text-xs font-bold uppercase tracking-widest transition-all shadow-[0_0_15px_rgba(220,38,38,0.3)] cursor-pointer"
        >
          {copied ? (
            <>
              <Check className="w-3.5 h-3.5 text-white" />
              <span>{translations.reportCopied}</span>
            </>
          ) : (
            <>
              <Copy className="w-3.5 h-3.5" />
              <span>{translations.copyReport}</span>
            </>
          )}
        </button>
      </div>
    </div>
  );
};
